# Generated by Django 4.0.6 on 2022-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='comment_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
