# Generated by Django 4.0.6 on 2022-08-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_members_id_alter_members_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
