# Generated by Django 4.0.6 on 2022-08-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_members_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_superuser',
        ),
    ]
