# Generated by Django 4.0.6 on 2022-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_members_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
