# Generated by Django 4.0.6 on 2022-08-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_members_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
