# Generated by Django 4.0.6 on 2022-08-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='image',
        ),
    ]
