# Generated by Django 4.0.6 on 2022-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_delete_attachment_remove_lectures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
    ]
