# Generated by Django 4.0.6 on 2022-08-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mentoring_chats',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mentoring_chats',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='age_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='mentorings.locations'),
        ),
    ]
