# Generated by Django 4.0.6 on 2022-08-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorings',
            name='location',
            field=models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorings.locations'),
        ),
    ]
