# Generated by Django 4.0.6 on 2022-08-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorings', '0002_alter_mentorings_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorings',
            name='field',
            field=models.CharField(choices=[('관리자', '관리자'), ('전문가 및 관련 종사자', '전문가 및 관련 종사자'), ('사무 종사자', '사무 종사자'), ('서비스 종사자', '서비스 종사자'), ('판매 종사자', '판매 종사자'), ('농림 어업 숙련 종사자', '농림 어업 숙련 종사자'), ('기은원 및 관련 기능 종사자', '기은원 및 관련 기능 종사자'), ('장치 기계 조작 및 조립 종사자', '장치 기계 조작 및 조립 종사자'), ('단순 노무 종사자', '단순 노무 종사자'), ('군인 및 학생', '군인 및 학생')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='location',
            field=models.CharField(choices=[('경기도', '경기도'), ('강원도', '강원도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도')], max_length=20),
        ),
    ]
