# Generated by Django 4.0.6 on 2022-08-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorings', '0005_mentoring_chats_user_id_mentorings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorings',
            name='limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mentorings',
            name='member_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
